### ISSUE TITLE
peripheral battery例程里没有加载eflash.c文件，且编译不会报错

### ISSUE THREAD

**Issue by munanqiu** [ingchips/ING918XX_SDK_SOURCE#167]
SDK8.3.4
现象：peripheral battery例程改成916后，可以正常编译（没有任何警告和错误），下载到芯片里无法运行。
原因：例程里调用了flash_prepare_factory_data接口，这个接口由BSP的eflash.c实现，但是例程没有加载eflash.c文件。
而且不仅没有加载文件，编译还没有任何警告和提示，因为使用DEF_WEAK_FUNC(int flash_prepare_factory_data(void))把函数声明为weak，如果用户没有自己定义函数体，默认函数体为提出一个断言（platform_raise_assertion），而main.c中没有断言部分的实现。

**Comment by zjli-2019** [comment]
resolved by commit 6080ef8d1f2f78bdfa5eba8d58e2d964f568edb5.
