### ISSUE TITLE
peripheral_adc.c中读取寄存器没有加volatile

### ISSUE THREAD

**Issue by munanqiu** [ingchips/ING918XX_SDK_SOURCE#168]
SDK： 8.3.0和8.3.4
文件：peripheral_adc.c
第128行
#define ADC_REG_VAL(reg)                ((*((uint32_t *)((APB_SARADC_BASE) + (reg)))))
uint32_t前面没有加volatile，如果开启优化，许多寄存器的操作会被优化掉，程序异常。
加上volatile后正常，加上后为
#define ADC_REG_VAL(reg)                ((*((volatile uint32_t *)((APB_SARADC_BASE) + (reg)))))

**Comment by zjli-2019** [comment]
resolve by PR #170.
