### ISSUE TITLE
调I2C+DMA的时候，传输7个字节数据没问题，但是传输8个字节数据时失败

### ISSUE THREAD

**Issue by qianxiansheng** [ingchips/ING918XX_SDK_SOURCE#177]
测试工程：https://github.com/ruiminw/projects/tree/main/IIC_916
I2C主机程序编译时打开的宏：USE_STDPERIPH_DRIVER,SIMU, I2C_MASTER, TIMER, R_W_DMA
I2C从机程序编译时打开的宏：USE_STDPERIPH_DRIVER,SIMU, I2C_SLAVE, TIMER, R_W_DMA
#define I2C_SCL         GIO_GPIO_9
#define I2C_SDA         GIO_GPIO_10

**Comment by ruiminw** [comment]
#181 provides the fix
