### ISSUE TITLE
918  开发者手册里flash介绍 

### ISSUE THREAD

**Issue by chaoximengzi** [ingchips/ING918XX_SDK_SOURCE#184]
能否补充下信息，例如flash的page 大小，擦除的最小单位，擦除page的时间需要多久，还有就是读flash用的是memcpy这部分原理是什么？

**Comment by zjli-2019** [comment]
https://github.com/ingchips/pg_ing918/issues

**Comment by zjli-2019** [comment]
Page、擦除的最小单位见：

https://github.com/ingchips/ING918XX_SDK_SOURCE/blob/c72474c01263e35507a8fa28a06e62b889447512/src/BSP/eflash.h#L48

`memcpy` 以 Flash 为源时，从软件看“没有原理”，由硬件处理。
