### ISSUE TITLE
9168 QSPI

### ISSUE THREAD

**Issue by qianxiansheng** [ingchips/ING918XX_SDK_SOURCE#193]
工程是在[QSPI_916](https://github.com/ruiminw/projects)的基础上改的
开启的宏分别是：主机：SPI_MASTER SPI_QSPI，从机：SPI_SLAVE SPI_QSPI

### 改动
- IO换了：

  ```C
  #define SPI_MIC_CLK         GIO_GPIO_19
  #define SPI_MIC_MOSI        GIO_GPIO_28
  #define SPI_MIC_MISO        GIO_GPIO_27
  #define SPI_MIC_CS          GIO_GPIO_18
  #define SPI_MIC_WP          GIO_GPIO_26
  #define SPI_MIC_HOLD        GIO_GPIO_20
  ```

- 频率改成2M：

  SPI_INTERFACETIMINGSCLKDIV_DEFAULT_2M

- ADDR长度改成3BYTES：

  SPI_ADDRLEN_3_BYTES

- 地址格式改成四线：

  apSSP_SetTransferControlAddrFmt(AHB_SSP0, SPI_ADDRFMT_QUAD_MODE);

- 地址传参改成0x123456：

  apSSP_WriteCmd(AHB_SSP0,0x123456,0x77);

### 问题

1. 看逻辑分析仪，发现地址部分输出的波形对不上：
![QSPI波形对不上](https://github.com/ingchips/ING918XX_SDK_SOURCE/assets/39825461/8f6ca0aa-b800-417c-83db-4daaa0665061)
感觉在输出地址的时候，MISO这条线(黄色DQ1)，没工作
0x123456 与 0x101454 相差0x022002

3. 作为从机时有API可以获取到命令和地址吗
4. 主机读从机的数据不对
![数据不对](https://github.com/ingchips/ING918XX_SDK_SOURCE/assets/39825461/87a214df-b121-4651-8158-dd7df703d9e4)

**Comment by ruiminw** [comment]
916 QSPI Slave不支持任意定义的addr+command模式，只有Master可以发出任意波形，Slave只支持command模式，QSPI_916工程已经删除，用QSPI_916_FLASH和QSPI_916_USER_COMMAND替换，前一个用来演示QSPI Master的读和写，后一个演示QSPI Slave的使用。
