### ISSUE TITLE
9168主机连接从机，主机开启低功耗模式时，连接会断开

### ISSUE THREAD

**Issue by qianxiansheng** [ingchips/ING918XX_SDK_SOURCE#194]
916的时候2住8从多链接，不开低功耗的时候可以正常连接，如果主机那边使能低功耗就会断开。怀疑和RC精度有关系，但是相同的固件，有的板子作为主机低功耗下不会断开，有的会。这个北京那边可以帮忙抓下log吗？这个现象几年前奉加的芯片上面遇到过，用forntline抓过的空口包时序上能看到就是握手错开了。

**Comment by qianxiansheng** [comment]
用ble_at_demo测试的情况，开启低功耗模式后过几秒就会断开连接
![image](https://github.com/ingchips/ING918XX_SDK_SOURCE/assets/39825461/d64345d9-617a-41d3-bec6-f496997032d6)

**Comment by zjli-2019** [comment]
使用 32k RC 时，可以

1. 调谐精度

    https://ingchips.github.io/application-notes/pg_power_saving_en/ch-api.html#internal-32k-rc-clock

1. 调整校准周期

    https://ingchips.github.io/application-notes/pg_power_saving_en/ch-api.html#k-clock
