### ISSUE TITLE
example下的reset handler源文件是空的

### ISSUE THREAD

**Issue by munanqiu** [ingchips/ING918XX_SDK_SOURCE#204]
工程源文件下没有内容
![image](https://github.com/ingchips/ING918XX_SDK_SOURCE/assets/64307678/6c995e89-bc86-4734-b43c-b02ee2f1a909)
![image](https://github.com/ingchips/ING918XX_SDK_SOURCE/assets/64307678/fe27ab68-6eee-4ce4-bd6d-8c6cf3a337e1)

**Comment by zjli-2019** [comment]
这个就是这样的。参考 doc/index.md.
