### ISSUE TITLE
board.c: buzzer not work

### ISSUE THREAD

**Issue by zjli-2019** [ingchips/ING918XX_SDK_SOURCE#206]
BUZZ_PIN is wrong for ING916 dev-boards.

https://github.com/ingchips/ING918XX_SDK_SOURCE/blob/f919e086e7a90e9d60f341a79c75db6b2e00241d/src/BSP/board.c#L502C10-L502C10

**Comment by NBDaner** [comment]
GIO_GPIO_8 corresponds to IO_SOURCE is IO_SOURCE_PWM0_A.
