### ISSUE TITLE
I/O Over BLE(Central) on 916

### ISSUE THREAD

**Issue by munanqiu** [ingchips/ING918XX_SDK_SOURCE#223]
I/O Over BLE(Central)这个例程默认是918的，切成916后编译不过去。
![image](https://github.com/ingchips/ING918XX_SDK_SOURCE/assets/64307678/1504ccb0-f5b4-43e5-8bbe-1fbe76288a15)

**Comment by zjli-2019** [comment]
916 RAM 小，切换后需要修改 buffer 大小。
