### ISSUE TITLE
NIM language usage

### ISSUE THREAD

**Issue by nikitos1550** [ingchips/ING918XX_SDK_SOURCE#241]
Hello!

I found nim forum thread https://forum.nim-lang.org/t/5509 from 2019. 
Seems before you had attempt to use nim in your sdk.
I briefly look through master code, there are some nim here https://github.com/search?q=repo%3Aingchips%2FING918XX_SDK_SOURCE++language%3ANim&type=code
Could you tell me what is current state of this experiment?

**Comment by zjli-2019** [comment]
There is an example using Nim: [Smart Home Hub](https://github.com/ingchips/ING918XX_SDK_SOURCE/tree/master/examples-gcc/smart_home_hub).

Bisides C/C++/Nim, it's also possible to develop BLE apps using [Zig](https://github.com/ingchips/ING918XX_SDK_SOURCE/tree/master/examples-gcc/central_fota), [Rust](https://ingchips.github.io/blog/2022-09-24-use-rust/), etc.
